[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "switchbot-actions"
version = "2.0.0"
authors = [
    {name = "Yoshio HANAWA", email = "y@hnw.jp"},
]
description = "A YAML-based automation engine for SwitchBot BLE devices with a Prometheus exporter."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = "<4.0,>=3.11"
license = { text = "MIT" }
keywords = ["switchbot", "automation", "prometheus", "ble", "home-automation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Home Automation",
    "Topic :: System :: Monitoring",
    "Typing :: Typed",
]
dependencies = [
    "pydantic (>=2.11.7,<3.0.0)",
    "pyswitchbot (>=0.69.0,<0.70.0)",
    "blinker (>=1.9.0,<2.0.0)",
    "prometheus-client (>=0.22.1,<0.23.0)",
    "ruamel-yaml (>=0.18.15,<0.19.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pytimeparse2 (>=1.7.1,<2.0.0)",
    "aiomqtt (>=2.4.0,<3.0.0)"
]

[project.urls]
"Homepage" = "https://github.com/hnw/switchbot-actions"
"Repository" = "https://github.com/hnw/switchbot-actions"
"Bug Tracker" = "https://github.com/hnw/switchbot-actions/issues"

[project.scripts]
switchbot-actions = "switchbot_actions.cli:cli_main"

[tool.pytest.ini_options]
#addopts = "--cov"
norecursedirs = ["tests/e2e"]

[tool.coverage.run]
source = ["switchbot_actions"]

[tool.coverage.report]
show_missing = true

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.format]
quote-style = "double"

[tool.pyright]
pythonVersion = "3.11"
reportMissingImports = true
reportMissingTypeStubs = false
venvPath = "."
venv = ".venv"

[tool.codespell]
# Words intentionally misspelled for testing purposes.
ignore-words-list = "temprature"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.10"
poetry = "^2.1.4"
pytest = "^8.4.1"
pytest-mock = "^3.14.1"
pytest-asyncio = "^1.1.0"
pytest-cov = "^6.2.1"
pre-commit = "^4.3.0"
pyright = "^1.1.404"
aiohttp = "^3.12.15"
